static const int Q = 9; // number of directions.

static const int cxs[] = { 0, 0, 1, 1, 1, 0, -1, -1, -1 };
static const int cys[] = { 0, 1, 1, 0, -1, -1, -1, 0, 1 };
static const int inverse_indexes[] = { 0, 5, 6, 7, 8, 1, 2, 3, 4 };
static const float weights[] = { 4.0 / 9.0, 1.0 / 9.0, 1.0 / 36.0, 1.0 / 9.0, 1.0 / 36.0, 1.0 / 9.0, 1.0 / 36.0, 1.0 / 9.0, 1.0 / 36.0 };

static const float PI = 3.14159265f;